### ISSUE TITLE
renaming "new" to something else?

### ISSUE THREAD

**Issue by maotora** [tunnckoCore/koa-rest-router#11]
Hi,

Thanks for making this awesome middleware!

While i know i can override, but i would suggest to rename the **controller** `new` to something else.

It doesn't throw any errors but as a "Js keyword" it gives other syntax highlighting and ....

Would `recent` do, instead of `new`?  <-- _it rhymed_

Thank you again :)

**Comment by tunnckoCore** [comment]
Thanks.

I understand you, I don't like it too, but it's like a standard. I don't think to change it, sorry.

**Comment by maotora** [comment]
Thank you.

It's good enough that you've provided someway of overriding the names. :)
